[versions]
minSdk = "21"
compileSdk = "36"
targetSdk = "36"

androidgradleplugin = "8.13.2"
lint = "32.0.0"
kotlin = "2.2.21"
ktlint = "1.8.0"

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-core = { module = "com.android.tools.lint:lint", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
plugin-androidgradleplugin = { module = "com.android.tools.build:gradle", version.ref = "androidgradleplugin" }
plugin-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.36.0" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.1.0" }

[plugins]
codequalitytools = { id = "com.vanniktech.code.quality.tools", version = "0.25.0" }
